version: '3'
services:
    multi-stage.one:
        build:
            context: .
            target: one
        container_name: one
#        environment:
#            APP_DEBUG: "false"

    multi-stage.two:
        build:
            context: .
            target: two
        container_name: two